language: go
sudo: true

go:
    - 1.11.x
    - 1.12.x
    - 1.13.x

install: OS=linux_amd64 sudo make codecov.install gotestsum.install

script: make ci

after_success: make codecov.push

notifications:
    email:
        on_success: change
        on_failure: always
