language: go

go:
    - 1.11.x

cache:
    directories:
        - vendor
        - on
        - tmp

install: sudo make deps

script: make all

notifications:
  email:
    on_success: change
    on_failure: always

# services:
# - docker
