language: go
sudo: true

go:
    - 1.11.x

before_install: make docker

script: make docker.all

notifications:
    email:
        on_success: change
        on_failure: always

services:
    - docker
