language: go

go:
    - 1.11.x

before_install: make docker

script: make docker.ci

after_success: make coverage.push

notifications:
    email:
        on_success: change
        on_failure: always

services:
    - docker
